version: "2.3"

services:
  klipper:
    image: burgrp/klipper-armv6
    container_name: klipper
    restart: always
    privileged: true
    volumes: 
      - /dev:/dev
      - /tmp:/tmp
      - /data/octoklip:/data
    environment:
      KLIPPER_LOG: "/data/klipper.log"
      KLIPPER_CONFIG: "/data/printer.cfg"

  octoprint:
    image: burgrp/octoprint-armv6
    container_name: octoprint
    restart: always
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /data/octoklip:/root
    labels:
      farm.device.services: "5000"

  webcam:
    image: burgrp/webcam-armv6
    container_name: webcam
    restart: always
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /tmp:/tmp
    labels:
      farm.device.services: "6000"
    