version: "2.3"

services:
  klipper:
    image: burgrp/klipper
    container_name: klipper
    restart: always
    privileged: true
    volumes: 
      - /dev:/dev
      - /tmp:/tmp
      - /data/octoklip:/data
    environment:
      KLIPPER_LOG: "/data/klipper.log"
      KLIPPER_CONFIG: "/data/printer.cfg"

  octoprint:
    image: burgrp/octoprint
    container_name: octoprint
    restart: always
    privileged: true
    pid: "host"
    ports:
      - 90:5000
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /data/octoklip:/root
    labels:
      farm.device.services: "90"
